AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: provided.al2023
    Architectures: ["arm64"]
    MemorySize: 3008
    Timeout: 30
    Tracing: Active
    Environment:
      Variables:
        PRODUCT_TABLE_NAME: !Ref Table
        LOG_GROUP_PREFIX: !Sub "/aws/lambda/net-8-aot-minimal-"
        LOAD_TEST_TYPE: "NET 8 native AOT Minimal API"

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: ApiBootstrap
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              !Ref Table
        - Version: "2012-10-17"
          Statement:
            - Sid: AllowStartQueries
              Effect: Allow
              Action:
                - logs:DescribeLogGroups
                - logs:StartQuery
              Resource: "*"
            - Sid: AllowGetQueryResults
              Effect: Allow
              Action: logs:GetQueryResults
              Resource: "*"
    Metadata:
      BuildMethod: makefile

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"