name: Metrics Lambda

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - metrics/src/logsToMetrics/**

jobs:
  build-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: checkout Repo
          uses: actions/checkout@v4 # https://github.com/actions/checkout

        - name: Build and Deploy
          uses: ./.github/actions/sam-build-and-deploy
          with:
            aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
            dotnet-version: '8.x'
            template-file-path: ./metrics/template.yaml
            stack-name: metrics-lambda
            s3-bucket-name: aws-dotnet-lambda-testing
