name: NET 8

on:
  workflow_dispatch:
  # push:
    # branches:
      # - main
    # paths:
      # - src/NET8/**

jobs:
  build-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: checkout Repo
          uses: actions/checkout@v4 # https://github.com/actions/checkout  

        - name: Build and Deploy
          uses: ./.github/actions/sam-build-and-deploy
          with:
            aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
            dotnet-version: '8.x'
            template-file-path: ./src/NET8/template.yaml
            stack-name: net-8-base
            s3-bucket-name: aws-dotnet-lambda-testing

  load-test-arm:
      needs: build-deploy
      runs-on: ubuntu-latest
      steps:
        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v4 # https://github.com/aws-actions/configure-aws-credentials
          with:
            role-to-assume: ${{ secrets.AWS_ROLE }}
            role-session-name: GitHub_to_AWS_via_FederatedOIDC
            aws-region: ${{ secrets.AWS_REGION }}

        - name: checkout Repo
          uses: actions/checkout@v4 # https://github.com/actions/checkout  

        - name: Run Load Tests
          uses: ./.github/actions/run-load-test
          with:
            api-endpoint: ${{ secrets.API_ENDPOINT_NET_8_ARM }}

  load-test-x86:
      needs: build-deploy
      runs-on: ubuntu-latest
      steps:      
        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v4 # https://github.com/aws-actions/configure-aws-credentials
          with:
            role-to-assume: ${{ secrets.AWS_ROLE }}
            role-session-name: GitHub_to_AWS_via_FederatedOIDC
            aws-region: ${{ secrets.AWS_REGION }}

        - name: checkout Repo
          uses: actions/checkout@v4 # https://github.com/actions/checkout  

        - name: Run Load Tests
          uses: ./.github/actions/run-load-test
          with:
            api-endpoint: ${{ secrets.API_ENDPOINT_NET_8_X86 }}

  generate-report-arm:
      needs: [load-test-arm]
      runs-on: ubuntu-latest
      steps:
        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v4 # https://github.com/aws-actions/configure-aws-credentials
          with:
            role-to-assume: ${{ secrets.AWS_ROLE }}
            role-session-name: GitHub_to_AWS_via_FederatedOIDC
            aws-region: ${{ secrets.AWS_REGION }}

        - name: checkout Repo
          uses: actions/checkout@v4 # https://github.com/actions/checkout  

        - name: Generate reports
          uses: ./.github/actions/generate-report
          with:
            api-endpoint: ${{ secrets.API_ENDPOINT_NET_8_ARM }}
            output-report-file-name: net-8-arm-output.md

  generate-report-x86:
      needs: [load-test-x86]
      runs-on: ubuntu-latest
      steps:
        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v4 # https://github.com/aws-actions/configure-aws-credentials
          with:
            role-to-assume: ${{ secrets.AWS_ROLE }}
            role-session-name: GitHub_to_AWS_via_FederatedOIDC
            aws-region: ${{ secrets.AWS_REGION }}

        - name: checkout Repo
          uses: actions/checkout@v4 # https://github.com/actions/checkout   

        - name: Generate reports
          uses: ./.github/actions/generate-report
          with:
            api-endpoint: ${{ secrets.API_ENDPOINT_NET_8_X86 }}
            output-report-file-name: net-8-x86-output.md
